# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tofuinit < Formula
  desc ""
  homepage "https://github.com/p0bailey/tofuinit"
  version "1.0.19"

  on_macos do
    url "https://github.com/p0bailey/tofuinit/releases/download/1.0.19/tofuinit_darwin_all.zip"
    sha256 "378c5de21c98e0e1131f1443ab53d187269ad35318394a50ab76427188d4870f"

    def install
      bin.install "tofuinit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/p0bailey/tofuinit/releases/download/1.0.19/tofuinit_linux_arm.zip"
      sha256 "bc0e1d8fbb3b19e09b2998dbb49ae258b874cc85a98535d45650c16b4cac0ebb"

      def install
        bin.install "tofuinit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/p0bailey/tofuinit/releases/download/1.0.19/tofuinit_linux_arm64.zip"
      sha256 "fb78ed80c4d433d375c114879f2fdd0e7d1ace06b6134220514410938564f06b"

      def install
        bin.install "tofuinit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/p0bailey/tofuinit/releases/download/1.0.19/tofuinit_linux_amd64.zip"
      sha256 "4148356e4e04d9b4f3d5802774f7b34501b614a8fa410fc7ebdf08daed79b285"

      def install
        bin.install "tofuinit"
      end
    end
  end
end
