# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tofuinit < Formula
  desc ""
  homepage "https://github.com/p0bailey/tofuinit"
  version "1.0.32"

  on_macos do
    url "https://github.com/p0bailey/tofuinit/releases/download/1.0.32/tofuinit_darwin_all.zip"
    sha256 "7487a5b31a41f70da29273e234f1873437456f99efa1e3e4171cdea0da13ccdc"

    def install
      bin.install "tofuinit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/p0bailey/tofuinit/releases/download/1.0.32/tofuinit_linux_arm64.zip"
      sha256 "4ce0119e124043fa3e6c905d015d31db8af2d90a5ffbdcedea77c64be625bdf2"

      def install
        bin.install "tofuinit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/p0bailey/tofuinit/releases/download/1.0.32/tofuinit_linux_amd64.zip"
      sha256 "9532ace99d279624588a7e2567bf6a76030b5368a6a93a334ff48923896616f8"

      def install
        bin.install "tofuinit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/p0bailey/tofuinit/releases/download/1.0.32/tofuinit_linux_arm.zip"
      sha256 "bbde27995f601272c81503102e298ab4c30ddb03fbd2be7f177e36faeec83647"

      def install
        bin.install "tofuinit"
      end
    end
  end
end
